eclipse-rcptt/org.eclipse.rcptt

- maven-plugin/rcptt-maven-util/src/main/java/org/eclipse/rcptt/maven/util/PlatformUtil.java
- runner/features/org.eclipse.rcptt.runner.runner-feature/feature.xml
- runner/pom.xml
- runner/product/rcptt.runner.product
From https://bugs.eclipse.org/bugs/show_bug.cgi?id=581959:
I run Maven on macOS with a JDK for aarch64.  My Maven build assembles an Eclipse product for aarch64 but rcptt-maven-plugin fails my build.
First, the "rcptt-maven-plugin:resources" goal fails to find my Eclipse product.  The console output shows:
> [INFO] Sys arch is aarch64
> [INFO] classifier is not specified for AUT, setting to macosx.cocoa.x86_64 by default
This is a bug in org.eclipse.rcptt.maven.util.PlatformUtil.getArch() which incorrectly always returns "x86_64" on macOS.  I can work around this issue by adding an explicit "aut/classifier" tag in my pom.
Next, the "rcptt-maven-plugin:execute" goal is executed which launches the runner which fails with a bunch of "Could not resolve module" errors.  When I inspect the …
> fix maven-plugin and runner not working with JDK for "macosx.aarch64"

- core/org.eclipse.rcptt.reporting/src/org/eclipse/rcptt/reporting/core/ReportHelper.java
- launching/org.eclipse.rcptt.reporting.html/src/org/eclipse/rcptt/reporting/html/FullSingleTestHtmlRenderer.java
- releng/Jenkinsfile.groovy
- releng/buildenv/ubuntu/Dockerfile
- runtime/tests/pom.xml
- watson/org.eclipse.rcptt.watson.core/src/org/eclipse/rcptt/sherlock/core/reporting/ReportBuilder.java
This is required by https://github.com/eclipse/org.eclipse.rcptt/pull/21
> Use Java 17 in CI

- launching/org.eclipse.rcptt.launching.ext/src/org/eclipse/rcptt/launching/ext/Q7ExternalLaunchDelegate.java
- rcp/org.eclipse.rcptt.launching.configuration/src/org/eclipse/rcptt/launching/configuration/Q7LaunchConfigurationDelegate.java
Do not use -eclipse.keyring by default.
> Fix Illegal option: 'e' in '-eclipse.keyring'

- runtime/tesla/org.eclipse.rcptt.tesla.gef/src/org/eclipse/rcptt/tesla/gef/GefProcessor.java
- runtime/tesla/org.eclipse.rcptt.tesla.gef/src/org/eclipse/rcptt/tesla/gef/TeslaGefAccess.java
The dispose listener of the graphical viewer is added to the FigureCanvas via a method reference, rather than an anonymous class.
The reflective operation which tries to retrieve this viewer by looking for the "this$0" variable no longer works, because this variable is now called "arg$1".
With this change, we check for either of those variables. Resolves #30
> Fix "no null" error during replay when using GEF 3.16 or newer

- build_runner.sh
- devenv/launches/RCPTT Runner.launch
- launching/org.eclipse.rcptt.launching.ext/src/org/eclipse/rcptt/launching/internal/target/TargetPlatformHelper.java
- rcp/contexts/org.eclipse.rcptt.ctx.preferences.ui/.project
- runner/org.eclipse.rcptt.runner/.classpath
- runner/org.eclipse.rcptt.runner/.settings/org.eclipse.jdt.core.prefs
- runner/org.eclipse.rcptt.runner/src/org/eclipse/rcptt/runner/util/AUTsManager.java
- runner/org.eclipse.rcptt.runner/src/org/eclipse/rcptt/runner/util/AutThread.java
Ignore AUT configuration if Runner is explicitly given a VM in command line. This changes the semantics of -autVM argument - now it takes priority over AUT's configuration.
Resolve VM paths relative to configuration file location.
Before this change, Runner logged errors even if  JVM was configured via command line:
```
Trying to use VM from application's ini file: ../Eclipse/features/net.openchrom.jre.macosx.cocoa.aarch64.feature_17.0.11/jre/jdk-17.0.11+9-jre/Contents/Home/lib/libjli.dylib
/private/tmp/Eclipse.app/../Eclipse/features/net.openchrom.jre.macosx.cocoa.aarch64.feature_17.0.11/jre/jdk-17.0.11+9-jre/Contents/Home/lib/libjli.dylibdoes not exist
AUT-0: Launch failed. Reason: FAIL: AUT requires aarch64 Java VM which cannot be found.
Please specify -autVM {javaPath} command line …
```
> Handle relative VM paths in AUT.ini on MacOS

- runtime/tesla/org.eclipse.rcptt.tesla.gef/src/org/eclipse/rcptt/tesla/gef/GefProcessor.java
The method getDrawerFigure() has been removed and getFigure() should be used instead. On older GEF releases, this method returns a plain IFigure, so to ensure backwards compatibility, one needs to do an explicit cast.
Fixes https://github.com/eclipse/org.eclipse.rcptt/issues/79
> Fix NoSuchMethodError when using GEF 3.19 or higher

- releng/RCPTT.setup
What it does:
- Check out the repository from GitHub
- Import all org.eclipse.rcptt projects
- Load the 2024-03 (or whatever else is selected) target platform
- Group projects by Bundle/Feature/Releng & RAP/Non-RAP
> Update Oomph setup file to work with Git repository

- rcp/contexts/org.eclipse.rcptt.ctx.preferences.ui/src/org/eclipse/rcptt/ctx/preferences/ui/PreferencesContextEditor.java
- runner/org.eclipse.rcptt.runner/src/org/eclipse/rcptt/runner/HeadlessRunnerApp.java
- runner/org.eclipse.rcptt.runner/src/org/eclipse/rcptt/runner/util/TestsRunner.java
Runner should fail on AUT launch error or if no tests are found.
This is a backward incompatible change.
Fixes [bug 572501](https://bugs.eclipse.org/bugs/show_bug.cgi?id=572501)
> Bug 572501: Do not suppress errors, fail if tests are not found

- README.md
It seems a redesign of the website broke many links.
See also https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/5510
> Fix user guide link

- releng/pom.xml
Tycho removed it in version 3
(https://github.com/eclipse-tycho/tycho/blob/main/RELEASE_NOTES.md#pack200 ).
Eclipse removed entirely and has been a no-op since 4.16 (2020-06) https://www.eclipse.org/lists/cross-project-issues-dev/msg18273.html . Java removed it since Java 14 https://openjdk.org/jeps/367 and was marked for removal since Java 11.
This is a prereq for moving the build to Tycho 3.
> Stop pack200 building

- releng/Jenkinsfile.groovy
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/5641#note_3255644
This allows Jenkins Kubernetes to work with mutable Docker tags.
> Trying to isolate build pods

- Jenkinsfile
- releng/Jenkinsfile
> Did you forget the `def` keyword? WorkflowScript seems to be setting a field named result (to a value of type Build) which could lead to memory leaks or other issues.
> Fix pipeline warning

- ecl/plugins/org.eclipse.rcptt.ecl.core/src/org/eclipse/rcptt/ecl/internal/core/ProcessStatusConverter.java
Reports contain following truncated trace:
```
java.io.IOException: Terminate failed
at org.eclipse.debug.core.Launch.terminate(Launch.java:298)
at org.eclipse.rcptt.debug.runtime.DebugContextProcessor$3.run(DebugContextProcessor.java:312)
at java.lang.Thread.run(Thread.java:1583)
```
> Fix Status loss for DebugException #92

- launching/org.eclipse.rcptt.launching.ext/src/org/eclipse/rcptt/internal/launching/ext/UpdateVMArgs.java
- rcpttTests/pom.xml
See https://github.com/eclipse-packaging/packages/issues/37 as modern Java VMs are pretty good at managing the heap size automatically. Restricting to tiny heap sizes also clashes with `-XX:+UseG1GC` which is the default for Eclipse RCP based IDEs now.
> Fix tiny heap sizes set by default

- launching/org.eclipse.rcptt.launching.ext/src/org/eclipse/rcptt/launching/ext/Q7ExternalLaunchDelegate.java
- modules/rap/bundles/launching/org.eclipse.rcptt.launching.rap/src/org/eclipse/rcptt/launching/rap/RcpttRapLaunchDelegate.java
- rcp/org.eclipse.rcptt.launching.configuration/src/org/eclipse/rcptt/launching/configuration/Q7LaunchConfigurationDelegate.java
- rcp/org.eclipse.rcptt.launching.ext.ui/src/org/eclipse/rcptt/internal/launching/ext/ui/AUTArgumentsTab.java
- runner/org.eclipse.rcptt.runner/src/org/eclipse/rcptt/runner/util/AutThread.java
This fixes a regression introduced in
2d132a197e4f3bbfe5de9ac413803f24e4548e71
The default value handling is required, because AUTArgumentsTab specifically deletes values matching the default.
> Bug 580941: Fix default value handling for OVERRIDE_SECURE_STORAGE

- dependencies/bundles/org.eclipse.rcptt.updates.aspectj.e44x/pom.xml
- dependencies/bundles/org.eclipse.rcptt.updates.external.dependencies.rap/pom.xml
- dependencies/bundles/org.eclipse.rcptt.updates.extra/pom.xml
- dependencies/bundles/org.eclipse.rcptt.updates.kepler/pom.xml
It's no longer supported by Tycho version used in the build. Fixes many "[WARNING] Parameter 'includePacked' is unknown for plugin 'tycho-p2-extras-plugin:4.0.12:mirror (mirror-update-site)'" in the build.
> Remove unrecognized includePacked parameter

- releng/Jenkinsfile.groovy
https://plugins.jenkins.io/pipeline-maven/#plugin-content-sensible-default-maven-parameters avoids spammy logs about download speeds and package sizes.
> Suppress Maven Download Messages on Jenkins

- ecl/plugins/org.eclipse.rcptt.ecl.data/.classpath
- ecl/plugins/org.eclipse.rcptt.ecl.data/.settings/org.eclipse.jdt.core.prefs
- launching/org.eclipse.rcptt.reporting.util/.settings/org.eclipse.jdt.core.prefs
JDT no longer supports generation of pre 1.8 bytecode (https://eclipse.dev/eclipse/news/news.html?file=4.33/jdt.html#removed-support-for-java7-and-below ). Such cases are silently treated as 1.8.
Also put o.e.jdt.core.prefs files in git control in order to be sure that JDT is fully instructed what to do based on content of Manifest file.
> Sync JDT settings

- ecl/tests/org.eclipse.rcptt.ecl.parser.test/src/org/eclipse/rcptt/ecl/parser/test/TestSession.java
- launching/org.eclipse.rcptt.launching/src/org/eclipse/rcptt/internal/launching/aut/OutputCaptureLaunchListener.java
- launching/org.eclipse.rcptt.reporting.html/src/org/eclipse/rcptt/reporting/html/HtmlReportRenderer.java
- launching/org.eclipse.rcptt.reporting.html/src/org/eclipse/rcptt/reporting/html/HtmlReporter.java
- launching/tests/org.eclipse.rcptt.reporting.html.tests/src/org/eclipse/rcptt/reporting/html/tests/VolatileContentFactory.java
- rcp/org.eclipse.rcptt.ui/src/org/eclipse/rcptt/ui/editors/PropertyCellEditor.java
- rcp/org.eclipse.rcptt.ui/src/org/eclipse/rcptt/ui/editors/ecl/EclInformationContol.java
- rcp/org.eclipse.rcptt.ui/src/org/eclipse/rcptt/ui/launching/ResourceLaunchConfigurationMigration.java
Replaced with java NIO's StandardCharsets for which Charsets members are aliases for.
> Stop using Guava's deprecated Charsets

- .mvn/extensions.xml
- releng/pom.xml
Full release notes available at
https://github.com/eclipse-tycho/tycho/blob/tycho-4.0.13/RELEASE_NOTES.md .
One of the important features is that now it works with Java 24 thanks to updated dependencies that fix
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2623 .
> Build with Tycho 4.0.13
